### ISSUE TITLE
Add exit number to highway in route resume

### ISSUE THREAD

**Issue by cibersheep** [costales/unav#1]
- Set a destination
- Simulate rute or start navigation
- Tap to show rute step-by-step view

Expected: to be able to know ahead the rute from origin to destination

![image](https://user-images.githubusercontent.com/6640041/68309427-b6d5dd00-00ae-11ea-8f9a-8b57fc656390.png)

Actual behaviour: if exiting from highway says turn right / keep to the right

For me could be helpful to have the highway exit number

![image](https://user-images.githubusercontent.com/6640041/68309295-7c6c4000-00ae-11ea-9725-b0664ec9b231.png)

**Comment by costales** [comment]
Hi @cibersheep 
Could you give me your example [from here](https://maps.openrouteservice.org/directions?n1=49.409445&n2=8.692953&n3=13&b=0&k1=en-US&k2=km)? 
Thanks!

**Comment by cibersheep** [comment]
Sure. Let's see:

https://maps.openrouteservice.org/directions?n1=39.554279&n2=2.707293&n3=17&a=39.430852,3.019209,39.59799,2.7111&b=0&c=0&k1=en-US&k2=km

I think this should be one of the point: https://maps.openrouteservice.org/directions?n1=39.552904&n2=2.703637&n3=17&a=39.430852,3.019209,39.59799,2.7111&b=0&c=0&k1=en-US&k2=km

but I see there's no exit information :(

**Comment by costales** [comment]
Hi,

Yes, appears it doesn't show the highway exit:

![image](https://user-images.githubusercontent.com/5886786/69476800-d410e800-0dde-11ea-8c12-48e7e434b1fe.png)

Previous router API did it.

I'll close this ticket then, OK?

Thanks for the feedback! ;) A hug.

**Comment by cibersheep** [comment]
Senquiu for the app :D
