### ISSUE TITLE
Request location at app start already

### ISSUE THREAD

**Issue by jonnius** [costales/unav#11]
Location service tends to be slow on Ubuntu Touch. Requesting the location when the app is started and not only after configuring the route would reduce the waiting time after configuring.

**Comment by costales** [comment]
Hi,
That was the 1st behavior of uNav. But, what is the point of using GPS (reducing the battery) if you are only checking the map or searching things?
A hug.

**Comment by jonnius** [comment]
Valid point. If you assume using uNav without GPS a common Use Case.
