### ISSUE TITLE
OSK covers search pages

### ISSUE THREAD

**Issue by cibersheep** [costales/unav#14]
- Tap on search TextField

OSK covers the ListView

**Comment by toraschi** [comment]
Hi may bee you meen this view when typing into the search felder? You can't see what your are typing
![screenshot20200313_175951226](https://user-images.githubusercontent.com/32172610/76643317-19575200-6555-11ea-9310-5e8b7ad19c17.png)

**Comment by toraschi** [comment]
Normal the list appears

**Comment by cibersheep** [comment]
Yes. Should be fixed with 
https://github.com/costales/unav/pull/16
