### ISSUE TITLE
2.5D street view 

### ISSUE THREAD

**Issue by suoko** [costales/unav#19]
Did you already try to make the view 3d ? I guess a fake 2.5D view are usually enough for turn by turn nav apps.
Maybe with Scene2D of Qt 3D ?

**Comment by costales** [comment]
Hi,
Not possible currently now, the map are image tiles.
But thanks for the idea!!
Best regards.

**Comment by suoko** [comment]
Image tiles are just square images right ?
Really, I don't know exactly how tiles work, but if that's the case, we can partially flip them
https://gofile.io/d/NqtPTF

**Comment by costales** [comment]
Hi,
Yes, they are square images. I need a vectorial map for allow that. 
It's not as easy as it sounds - besides the rotation itself, you need to extend all the projection logic for all events to work with rotated maps correctly, extend touch logic to allow rotation with fingers, change the tile loading algorithm (it will become more complex in rotated case than just a requesting rectangle of tiles), and many other nuances.
A hug!
--
Costales.

**Comment by suoko** [comment]
I even found this, but I bet you know that: https://gofile.io/d/ERFB2K
I don't get why logic should change, I'm talking only about the map display ... 
Can I load you project in qtcreator ?

**Comment by costales** [comment]
Hi,
When you touch on the map, it's a point in 2D, if you moved the image the
touch doesn't correspond with the real point touched.
I don't know about qtcreator, I think you have to use clickable
https://clickable-ut.dev/en/latest/
Any way, the way is to migrate that map to a vector map :)
Best regards.
--
Costales.

**Comment by suoko** [comment]
Vector tiles are available too
https://openmaptiles.org/

Il mer 6 mag 2020, 23:17 Costales <notifications@github.com> ha scritto:
