### ISSUE TITLE
Rute simulation for car is broken 

### ISSUE THREAD

**Issue by toraschi** [costales/unav#20]
Hello on my nexus 5 I is the rooting simulation broke but only if I use car mode with bicycle or by foot it works. for test choose  two destinations an try to simulate clicking the botton with the two arrows. You won't see the blue enhancement . if you switch too the bicycle mode you see the track immediately.

**Comment by costales** [comment]
Hi, uNav 3 will be released soon. Please, come back here if the issue persist. uNav 2 is deprecated. Thanks
