### ISSUE TITLE
deb or Flatpak package

### ISSUE THREAD

**Issue by baarkerlounger** [costales/unav#22]
Is it possible to run uNav on plain Debian derivatives that don't have snap/ubuntu touch specific tools installed.

Would it be possible to package this as a .deb or flatpak to make installation on Debian systems easier? Thinking particularly of PinePhone Mobian.

**Comment by costales** [comment]
Hi @baarkerlounger ,

It's needs the UT libraries. Anyway, even with that, the access to things as the GPS, media... I think is complicate.

A .deb would increase the users too and it could be a spam to the online APIs either.

Best regards.

**Comment by baarkerlounger** [comment]
Not entirely sure what is meant by increasing users could be a spam to online APIs? Users could presumably add their own API keys for backened services if needed?

Anyway though - happy to close this if it's not really feasible or planned.
