### ISSUE TITLE
use alert audio stream for voice directions

### ISSUE THREAD

**Issue by padu22** [costales/unav#23]
On UT, voice directions are currently mixed with audio streams from other apps at the same volume level.  PulseAudio provides  "alert" audio streams.  When an alert audio stream is played all other audio's volume is automatically reduced, making the alert audio stream more prominent.

A UT example of alert audio streams is the shutter sound of the camera app.  I cannot provide more technical information about this, but this issue is also discussed at UBports forum thread [sound issue playing music and voice navigation](https://forums.ubports.com/topic/4783/sound-issue-playing-music-and-voice-navigation).

**Comment by costales** [comment]
Thanks for the feedback @padu22 !! :)

The sound is played by a HTML container, then I can't call that alert call to the phone in that moment.

I'm sorry.
