### ISSUE TITLE
waiting for a gps signal

### ISSUE THREAD

**Issue by casineda** [costales/unav#24]
Device: opo
Channel: stable Ota 12
Issue description: when run  navigation the app stand on waiting for a gps signal. 
don't start nothing

**Comment by costales** [comment]
Hi, do you have signal with other apps? Like sensor status or pure maps. best regards

-- 
Sent using Dekko from my Ubuntu device

**Comment by casineda** [comment]
Hi saw that I have the same problem with all apps needing gps signal.
With my opo I'have to wait a lot of time: about 30 minutes and more.
If I'm in indoor I don't get gps signal at all. In outdoor after 30 minutes I can hope to get signal.

**Comment by costales** [comment]
Hi, yes, it is normal, becauseit uses GPS and not AGPS. Please fill a issue to ubports in gitlab. Best regards.

-- 
Sent using Dekko from my Ubuntu device
