### ISSUE TITLE
Repetitive route re-calculation

### ISSUE THREAD

**Issue by zlamalp** [costales/unav#25]
Hi, I noticed cyclic route re-calculation on RC. I set the destination and navigation by the car and started the trip.
I was actually sitting in a park on the same place all the time (nearest street was cca 50m). Map was rotating as GPS was probably guessing my direction.
After cca 2 minutes, it "noticed" I was outside of the expected route and triggered re-calculation. It found exactly the same route, since it was the nearest street and started the trip again. But then it happened again in a few seconds and then it repeated immediately without any delay.

Is there any wait time (at the trip start) before one enters the route (starting point)? I don't think, that GPS location changed that much (since I was sitting on the same place), that it should be re-calculating the route just because I'm "still staying" outside of the route.

**Comment by costales** [comment]
Hi,

Good point, probably the start point is far from your position and uNav recalculate again. 

I have to fix this for the release.

Well done @zlamalp you find a good bug :)

**Comment by costales** [comment]
@zlamalp Could you share me here or by private in Telegram (user costales) the origin and destination coordinates? You can get them sharing from uNav. Thanks in advance!

**Comment by costales** [comment]
Fixed for uNav 3. Thanks mate!
