### ISSUE TITLE
Blank screen after few minutes of navigation

### ISSUE THREAD

**Issue by zlamalp** [costales/unav#26]
After cca 5 minutes of navigating, the map screen becomes blank and it stops the navigation (eg. no sound instruction before turning, no map, location etc.). App as a whole is working (I can enter the settings tabs), but in order to get the navigation back I must restart the app.

OSM scout server is running at the background and by its logs, its not asked for the tiles after that. It is set to not be suspended, so it should be ok from this point of view.

Generally when navigating, my location update is lagging on my Nexus 5 very much. It shows location in the middle of the street (while driving) when I reach the street end (cca 50m off). I believe it takes too much time to provide the new tiles or display and rotate them in the map view and after some time it will cause the blank screen.

This happened multiple times on various places (every time navigation by car).

I have some log messages, but I'm not sure they are relevant, since they didn't appeared at the same time as a blank screen.
```
Too many warnings were give. Performance monitoring stops.
(It also logged, that last frame took cca 50ms to render multiple times).
```
```
shm_open() failed: Permission denied

qml: [JS] .....index.html:0 Uncaught (in promise) AbortError: The play() request was interrupted by a call to pause(). https://goo.gl/LDLk22

WebEngine complied with X11 support however qpa backend is not xcb. This may fail.
```
and there is also message, that AppArmor policy prevented the app from sending some message to com.canonical.libertine.Service.

**Comment by costales** [comment]
Hi,

Yes, I saw that too. The map is a HTML container and the system kills it if the CPU needs power :( I don't know how to fix this.

In offline, as it's vector map, you'll see that more. In online mode, you shouldn't see it so often.

I'll leave this issue for the future.

Thanks for the feedback.

**Comment by hankschwie** [comment]
Hi!

I have the same issue on a fairphone2. The device gets very warm; while navigating I experienced the blank screens with OSM scout server; with online maps the whole device crashes and reboots, longest time working was about 20 minutes.

Could it be a hardware related problem the fairphone2 has? I have tried different channels, but experienced this on stable, rc and dev.

**Comment by costales** [comment]
Hi,
I think is because the CPU has a high load and kills the app container. No fix for that. In other devices as Volla it doesn't happen.
Best regards.
