### ISSUE TITLE
make version for regular linux phone

### ISSUE THREAD

**Issue by paju1986** [costales/unav#32]
It would be nice to be able to install this outside of ubuntu touch on other linux distributions for the pinephone and librem5 maybe in the form of flatpak?

**Comment by costales** [comment]
Hi, thanks for the idea, but I'm compromised with Ubuntu & UBPorts and uNav wants to be a reason for switching to Ubuntu Touch. 
Anyway, please, understand that I create software (uNav, Gufw, Folder Color, aNoise...) for me and then, as I believe in libre software, I released them for the community too. But I'm not working on demand and I'm not creating or maintaining software in platforms I don't use.
Best regards.
