### ISSUE TITLE
Research localisation field does not auto complete

### ISSUE THREAD

**Issue by lutin11** [costales/unav#34]
On version 3.41
Click on the magnifying glass
In the input field write 'Pont saint' it should help to complete the field and purpose 'Pobt saint Martin' as exemle.
It did works on the legacy Unav
Thanks for your work
The log file can be found there:
http://paste.ubuntu.com/p/yptzNdCZ72/

**Comment by costales** [comment]
Hi, but uNav never had autocomplete :O 
Best regards.

**Comment by lutin11** [comment]
> Hi, but uNav never had autocomplete :O
> Best regards.

ah, I thought it had.
Sorry for disturbing.

**Comment by costales** [comment]
Don't worry, you're welcome!
