### ISSUE TITLE
[Feature request] Simulation

### ISSUE THREAD

**Issue by garro95** [costales/unav#35]
One feature that I used a lot in the previous version of uNav was path simulation. 
It looks like this feature is not available in uNav 3 anymore.

Is it possible to bring it back?

**Comment by costales** [comment]
Hi,

It's in Search page, available from September
https://twitter.com/costalesdev/status/1307793760277934080

Best regards.

**Comment by garro95** [comment]
Oh, now I see. To be honest, I found it more intuitive in uNav 2 though.
I really appreciate your work. Thanks.

Best regards

**Comment by costales** [comment]
Hi,

Yes, it could be more intuitive before, but in uNav 3 I was looking for integration: Everything about navigation (search, simulate, load track, search coordinates...) in one page: the search page! :)

A hug
