### ISSUE TITLE
Bulgarian voice for uNAV

### ISSUE THREAD

**Issue by deyanyosifov** [costales/unav#37]
Hello,

I would like to provide a Bulgarian voice for the uNav app.

My firstname and lastname for the credits: Deyan Yosifov
Name of my language: Bulgarian
Name of my language in my language: Български
ISO code: bg

Best regards,
Deyan Yosifov

[unav_bg-01.tar.gz](https://github.com/costales/unav/files/5469627/unav_bg-01.tar.gz)

**Comment by costales** [comment]
Thanks! 
Your voice was uploaded and you should see it on uNav.
A hug!
