### ISSUE TITLE
Add generic build instructions

### ISSUE THREAD

**Issue by Kohoshi12** [costales/unav#42]
Build instructions will be useful for making uNav available for more Linux distribuitions.

**Comment by costales** [comment]
Hi,

uNav is for Ubuntu Touch in mind, with its libraries & API keys, then other distribution should replace the API Keys.

With this replace, uNav will be a production version:

`sed -i '/TESTING BEGIN/,/TESTING END/d' unav/nav/index.html`

Remember to replace the [test stadiamaps API key](https://github.com/costales/unav/blob/master/nav/class/WebAPI.js#L265) in unav/nav/class/WebAPI.js

Best regards,
