### ISSUE TITLE
Won't detect my location

### ISSUE THREAD

**Issue by codinghedgehog-python** [costales/unav#43]
I'm testing uNav on Xperia X (F5121) and Meizu 5 Pro both running Ubuntu Touch.
On Meizu the app sometimes takes couple of minutes before it finds my location and
sometimes it doesn't find it at all (yes GPS is on) .
On Xperia I've tested it today and it didn't find my location even after waiting for 5 minutes.
It should be almost immediate detection.

Let me know if you need any details.

**Comment by costales** [comment]
Hi,
Please, report it to the UBPorts support.
uNav gets the position from the system, if the system doesn't return a
position, I can't do anything about it.
Best regards,
--
Costales.
