### ISSUE TITLE
Hope to add some support

### ISSUE THREAD

**Issue by jidro** [costales/unav#47]
Hope to add support for Baidu Map car version or AMAP map car version，thanks

**Comment by costales** [comment]
Hi, sorry, but I don't understand the request. Are you talking about to include tiles map of Baidu or AMAP? Thanks.

**Comment by jidro** [comment]
Yes, because I am not a particularly about code and programming of this kind of knowledge, has been using ubuntu touch, but also have been using this software, but the feeling for China's support is not particularly friendly, so I hope can increase some support on car machine version of the map, seems to be similar to the navi map, Download it in ZIP format, so if possible, can you add support for this map file format, thanks.

**Comment by costales** [comment]
Hi, I'm sorry, uNav only uses free (as freedom) maps, and Baidu is not free. 
Best regards.
