### ISSUE TITLE
Russian voice for uNAV

### ISSUE THREAD

**Issue by niaproxy** [costales/unav#48]
Greetings!

I made Russian female voice for the uNav app.

My firstname and lastname for the credits: Ivan Samokhin
Name of my language: Russian
Name of my language in my language: Русский
ISO code: ru

[unav_ru-01.tar.gz](https://github.com/costales/unav/files/7329143/unav_ru-01.tar.gz)

**Comment by niaproxy** [comment]
And also new text translation for russian available at poeditor.com

**Comment by costales** [comment]
Hi @niaproxy 
Thanks for your contribution!
The voices are already in uNav. The translations will be in the next release :)
A hug!
