### ISSUE TITLE
Small mistake in OpenStore listing

### ISSUE THREAD

**Issue by Netherquark** [costales/unav#49]
[Here](https://open-store.io/app/navigator.costales), the following sentence is visible:
![image](https://user-images.githubusercontent.com/65618735/138047702-3ab86164-c3f6-4243-b450-0a70698bcc8e.png)

This doesn't seem to make sense. I think should be:

> If you like uNav 2 more, you can download it from here: https://github.com/costales/unav/releases/

**Comment by costales** [comment]
Thanks for the tip! It was fixed. Best regards!
