### ISSUE TITLE
[Improvement] Smoother motion and more incremental zooming while driving?

### ISSUE THREAD

**Issue by WNYmathGuy** [costales/unav#5]
I don't know how difficult it would be to implement the following, but these two items bug me a bit visually: 
1. the map jumps instead of smoothly moving and also does strange minor jumping angular rotations, 
1. the zoom jumps too many levels at a given speed (_not sure if speed is the reason_). 

Both are visually irritating. Bear in mind, I'm older than 50, and I'm using a Nexus 5 which has been through a lot in its life so far. Also, I had the jumping and zooming work the same for online mapping as I did with offline mapping. I have a large set of offline tiles now and they go from zoom 8 to 17, and well beyond where I am likely to drive. If too many tiles may be the culprit, I'll gladly rework my offline set to experiment. Also, also I don't know how to identify zoom levels relative to their rendering in the uNav app, so I guess at them below.

I can't say how many pixels the map jumps while driving or if it's speed-sensitive because I don't watch the map at all times :smile:, but I believe it's normally at zoom level 16 (500 ft / 200 m is the scale on my screen) and my velocity is below 45 MPH / 70 KPH when I see the map moving with studders or jerks. At that zoom level, the jump is about 3 to 5 millimeters and the timing is a bit quicker than one second (_my guess is it's the GPS poll rate of uNav?_). It seems like a reading of the accelerometer would be a great local proxy for the exact position between GPS updates. The vector from the 3-axis should be that 9.8m/(s*s) or whatever minimum the device seems to deliver as it's minimum. When it's greater than that, the program could move the tiles based on that to guess the actual position while awaiting the confirmation of the next GPS reading. This guessing could be used to smoothly move the tiles under the viewing window instead of jumping. 

On the rotation thing, I have no idea why this is happening, or how the magic blue line gets onto the road surface of a tile, but I'm guessing the jumpy rotation is due to loose or inaccurate GPS readings and uNav guessing physical direction based on the difference between GPS readings. _I'm fully aware of how often I guess wrong about how things work_ :wink:. What I think might be a better way to decide what rotational angle to turn the tiles, is the tangent line of the current motion of the device relative to the blue line on the tile. 

The zoom in zoom out I'm experiencing seems to happen at about 45 MPH / 70 KPH and it goes from that previously mentioned 16 zoom level directly to zoom level 13 (5000 ft / 1000 m is the scale on my screen). It's visually jarring for it to jump that many zoom levels in an instant. I can only guess that it's a speed-sensitive decision to select the zoom factor. If so, that's great, but why the big jump's and why don't I ever see other zoom levels while driving at sustained speeds between 10 & 70 KPH? If I was going to guess a better way to decide zoom levels: 

- I would decide to go visually up (from higher zoom level tile folder numbers to lower) based on the moving average of the last 3 GPS calculated velocities with respect to where they are placed on the blue line on the tiles,
- and I would visually go down (lower zoom level folder tile numbers to higher) based on the moving average of the last 7 GPS calculated velocities, a large dropping in the velocity of the device based on the accelerometer or as the distance to the next turn gets smaller. The distance to a turn would be the first precedence, the accelerometer reading changes the second precedence and the average velocity the last.

If I'm the only one experiencing this I'll be a bit embarrassed :blush:, and I'll gladly close the issue or won't mind if somebody else does.

**Comment by costales** [comment]
Hi,

Smooth movement: I tried in the past, but there was an issue with openlayers, moving from 350º to 5º it's rotating the map as no clockwise rotation and it's crazy.
I had to change the logic either (stay 1 position back for knowing where to go) and I experienced a few weird freezes.

Jumps: As it's working now is the meters and the rotation between previous and current position.

Zoom: Honestly I tried so much uNav, more zoom will have the same map, line, everything with the same size. And less zoom could give you not time for see the exit on an highway :)

A hug!
