### ISSUE TITLE
synchronus with Phonetrack

### ISSUE THREAD

**Issue by lutin11** [costales/unav#52]
This is not a bug but a feature request.
Would it be possible to have the option to export gpx log file to remote server ?
As exemple II would be interesting to send it to Nextcloud phone track as https://apps.nextcloud.com/apps/phonetrack
Thanks a lot

**Comment by costales** [comment]
Hi,
    But uNav is not using a GPX log :O
    Best regards.
    
    ---
CostalesMessage ID: ***@***.***>
    
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/costales/unav/issues/52",
"url": "https://github.com/costales/unav/issues/52",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by moameen1** [comment]
Hi @costales Looked at existing documentation on Ubports/unav.me.
Not sure 
1.why it doesnt detect current location instantly
Not much documented how to use this app.Do we have any documentation around this to troubleshoot etc?

Thanks
Am

**Comment by costales** [comment]
Hi, as I don't plan to include save GPX, I'll close this one. Thanks for the feedback
