### ISSUE TITLE
unav app won't install anymore

### ISSUE THREAD

**Issue by Maik-aD** [costales/unav#55]
The unav app won't install anymore on my Volla Phone 22 and Volla Phone X with  16.04 since you changed the app to the 20.04 Focal base. However 20.04 hasn't been released as of yet, please make the app available again for 16.04. Many thanks in advance and warm regards.

Maik

**Comment by costales** [comment]
Thank you for the feedback! Really appreciated!

It's an OpenStore issue. I created this bug https://gitlab.com/theopenstore/openstore-meta/-/issues/351

Best regards.

**Comment by costales** [comment]
Just as information, now it should work :) Best regards and thank you for the feedback!

**Comment by Maik-aD** [comment]
> Just as information, now it should work :) Best regards and thank you for the feedback!

Thank you so much. The app installed without any issues on both phones now. Keep up the great work. :)
